[env:rpipicow]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipicow
framework = arduino
board_build.core = earlephilhower
lib_deps =
    WiFi
    HTTPClient
build_flags =
    -DARDUINO_RASPBERRY_PI_PICO_W
    -DUSE_TINYUSB
board_build.arduino.earlephilhower.usb_speed = default
board_build.arduino.earlephilhower.usbstack = tinyusb
monitor_speed = 115200
build_src_filter = +<*>
